services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - 8766:80
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Europe/Madrid
      - DB_CONNECTION=sqlite
    volumes:
      - /portainer/Files/AppData/Config/speedtest-tracker2:/config
    restart: unless-stopped