version: "3.0"
services:
  aos:
    restart: always
    image: axelor/aos-preview-app
    ports:
      - "10080:8080"
    environment:
      APP_LANGUAGE: en
      APP_DEMO_DATA: true
      APP_LOAD_APPS: true
    volumes:
      - /portainer/Files/AppData/Config/aos/data:/app/data
      - /portainer/Files/AppData/Config/aos/postgresql:/var/lib/postgresql
    