version: '3.0'
services:
  thingsboard:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - /portainer/Files/AppData/Config/ThingsBoard/data:/data
      - /portainer/Files/AppData/Config/ThingsBoard/logs:/var/log/thingsboard